name: flight_delay
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.12.7
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - asttokens==3.0.1
      - attrs==25.4.0
      - catboost==1.2.8
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fonttools==4.61.1
      - graphviz==0.21
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - narwhals==2.13.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numba==0.63.1
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - patsy==1.0.2
      - pillow==12.0.0
      - platformdirs==4.5.1
      - plotly==6.5.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rpds-py==0.30.0
      - scikit-learn==1.5.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - shap==0.49.1
      - six==1.17.0
      - slicer==0.0.8
      - stack-data==0.6.3
      - statsmodels==0.14.6
      - threadpoolctl==3.6.0
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - watermark==2.5.1
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.15
      - xgboost==3.1.2
      - zipp==3.23.0